name: Build OpenFlux for iSH Terminal (Linux x86)

on:
  workflow_dispatch:

jobs:
  build-ish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Install dependencies
      run: go mod tidy

    - name: Compile for iSH Emulator
      run: |
        export CGO_ENABLED=0
        export GOOS=linux
        export GOARCH=386
        go build -o openflux-ish main.go

    - name: Upload iSH Binary
      uses: actions/upload-artifact@v4
      with:
        name: openflux-ish-binary
        path: openflux-ish